package bean;

// default package
// Generated Feb 1, 2018 1:02:35 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KgPred generated by hbm2java
 */
@Entity
@Table(name = "kg_pred", catalog = "kg_mp")
public class KgPred implements java.io.Serializable {

	private int prId;
	private String prUri;
	private String prLabel;
	private Integer prFreq;

	public KgPred() {
	}

	public KgPred(int prId) {
		this.prId = prId;
	}

	public KgPred(String prUri, String prLabel, Integer prFreq) {
		this.prUri = prUri;
		this.prLabel = prLabel;
		this.prFreq = prFreq;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "pr_id", unique = true, nullable = false)
	public int getPrId() {
		return this.prId;
	}

	public void setPrId(int prId) {
		this.prId = prId;
	}

	@Column(name = "pr_uri", length = 300)
	public String getPrUri() {
		return this.prUri;
	}

	public void setPrUri(String prUri) {
		this.prUri = prUri;
	}

	@Column(name = "pr_label", length = 200)
	public String getPrLabel() {
		return this.prLabel;
	}

	public void setPrLabel(String prLabel) {
		this.prLabel = prLabel;
	}

	@Column(name = "pr_freq")
	public Integer getPrFreq() {
		return this.prFreq;
	}

	public void setPrFreq(Integer prFreq) {
		this.prFreq = prFreq;
	}
}
