package bean;

// default package
// Generated Feb 1, 2018 4:19:36 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KgPredBucket generated by hbm2java
 */
@Entity
@Table(name = "kg_pred_bucket", catalog = "kg_mp")
public class KgPredBucket implements java.io.Serializable {

	private Integer pbId;
	private KgPred kgPred;
	private String pbUri;

	public KgPredBucket() {
	}

	public KgPredBucket(KgPred kgPred, String pbUri) {
		this.kgPred = kgPred;
		this.pbUri = pbUri;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pb_id", unique = true, nullable = false)
	public Integer getPbId() {
		return this.pbId;
	}

	public void setPbId(Integer pbId) {
		this.pbId = pbId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pb_pr_id")
	public KgPred getKgPred() {
		return this.kgPred;
	}

	public void setKgPred(KgPred kgPred) {
		this.kgPred = kgPred;
	}

	@Column(name = "pb_uri", length = 500)
	public String getPbUri() {
		return this.pbUri;
	}

	public void setPbUri(String pbUri) {
		this.pbUri = pbUri;
	}

}
