package bean;

// default package
// Generated Feb 1, 2018 1:02:35 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KgPredMap generated by hbm2java
 */
@Entity
@Table(name = "kg_pred_map", catalog = "kg_mp")
public class KgPredMap implements java.io.Serializable {

	private int pmId;
	private KgPred kgPred;
	private KgRule kgRule;

	public KgPredMap() {
	}

	public KgPredMap(int pmId) {
		this.pmId = pmId;
	}

	public KgPredMap(KgPred kgPred, KgRule kgRule) {
		this.kgPred = kgPred;
		this.kgRule = kgRule;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PM_ID", unique = true, nullable = false)
	public int getPmId() {
		return this.pmId;
	}

	public void setPmId(int pmId) {
		this.pmId = pmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pm_pr_id")
	public KgPred getKgPred() {
		return this.kgPred;
	}

	public void setKgPred(KgPred kgPred) {
		this.kgPred = kgPred;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pm_rl_id")
	public KgRule getKgRule() {
		return this.kgRule;
	}

	public void setKgRule(KgRule kgRule) {
		this.kgRule = kgRule;
	}

}
