package bean;

// default package
// Generated Feb 1, 2018 1:02:35 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KgRule generated by hbm2java
 */
@Entity
@Table(name = "kg_rule", catalog = "kg_mp")
public class KgRule implements java.io.Serializable {

	private int rlId;
	private String rlPropval;
	private Integer rlPropfreq;

	public KgRule() {
	}

	public KgRule(int rlId) {
		this.rlId = rlId;
	}

	public KgRule(String rlPropval, Integer rlPropfreq) {
		this.rlPropval = rlPropval;
		this.rlPropfreq = rlPropfreq;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rl_id", unique = true, nullable = false)
	public int getRlId() {
		return this.rlId;
	}

	public void setRlId(int rlId) {
		this.rlId = rlId;
	}

	@Column(name = "rl_propval", length = 500)
	public String getRlPropval() {
		return this.rlPropval;
	}

	public void setRlPropval(String rlPropval) {
		this.rlPropval = rlPropval;
	}

	@Column(name = "rl_propfreq")
	public Integer getRlPropfreq() {
		return this.rlPropfreq;
	}

	public void setRlPropfreq(Integer rlPropfreq) {
		this.rlPropfreq = rlPropfreq;
	}

}
