package bean;

// default package
// Generated Feb 1, 2018 4:19:36 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KgRulePropvalBucket generated by hbm2java
 */
@Entity
@Table(name = "kg_rule_propval_bucket", catalog = "kg_mp")
public class KgRulePropvalBucket implements java.io.Serializable {

	private Integer rpbId;
	private KgRule kgRule;
	private String rpbPropval;

	public KgRulePropvalBucket() {
	}

	public KgRulePropvalBucket(KgRule kgRule, String rpbPropval) {
		this.kgRule = kgRule;
		this.rpbPropval = rpbPropval;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RPB_ID", unique = true, nullable = false)
	public Integer getRpbId() {
		return this.rpbId;
	}

	public void setRpbId(Integer rpbId) {
		this.rpbId = rpbId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RPB_RL_ID")
	public KgRule getKgRule() {
		return this.kgRule;
	}

	public void setKgRule(KgRule kgRule) {
		this.kgRule = kgRule;
	}

	@Column(name = "RPB_PROPVAL", length = 500)
	public String getRpbPropval() {
		return this.rpbPropval;
	}

	public void setRpbPropval(String rpbPropval) {
		this.rpbPropval = rpbPropval;
	}

}
