package bean;

// default package
// Generated Feb 1, 2018 1:02:35 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KgRuleMap generated by hbm2java
 */
@Entity
@Table(name = "kg_rule_map", catalog = "kg_mp")
public class KgRuleMap implements java.io.Serializable {

	private int rmId;
	private KgRule kgRule;
	private TriplePatternMap triplePatternMap;

	public KgRuleMap() {
	}

	public KgRuleMap(int rmId) {
		this.rmId = rmId;
	}

	public KgRuleMap(KgRule kgRule, TriplePatternMap triplePatternMap) {
		this.kgRule = kgRule;
		this.triplePatternMap = triplePatternMap;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rm_id", unique = true, nullable = false)
	public int getRmId() {
		return this.rmId;
	}

	public void setRmId(int rmId) {
		this.rmId = rmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rm_rl_id")
	public KgRule getKgRule() {
		return this.kgRule;
	}

	public void setKgRule(KgRule kgRule) {
		this.kgRule = kgRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rm_tpm_id")
	public TriplePatternMap getTriplePatternMap() {
		return this.triplePatternMap;
	}

	public void setTriplePatternMap(TriplePatternMap triplePatternMap) {
		this.triplePatternMap = triplePatternMap;
	}

}
